// Code generated by protoc-gen-go. DO NOT EDIT.
// source: alpacalabs/pagination/v1/page.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Sort int32

const (
	Sort_SORT_UNSPECIFIED Sort = 0
	Sort_SORT_ASC         Sort = 1
	Sort_SORT_DESC        Sort = 2
)

var Sort_name = map[int32]string{
	0: "SORT_UNSPECIFIED",
	1: "SORT_ASC",
	2: "SORT_DESC",
}

var Sort_value = map[string]int32{
	"SORT_UNSPECIFIED": 0,
	"SORT_ASC":         1,
	"SORT_DESC":        2,
}

func (x Sort) String() string {
	return proto.EnumName(Sort_name, int32(x))
}

func (Sort) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_89006c53d509bbb7, []int{0}
}

// CursorRequest provides metadata for cursor pagination.
// See https://developer.twitter.com/en/docs/basics/cursoring.
type CursorRequest struct {
	// Cursor is inclusive.
	Cursor string `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	// Count is how many elements the client wishes to fetch.
	// Endpoints should set a maximum number of elements that can be returned.
	Count                int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CursorRequest) Reset()         { *m = CursorRequest{} }
func (m *CursorRequest) String() string { return proto.CompactTextString(m) }
func (*CursorRequest) ProtoMessage()    {}
func (*CursorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_89006c53d509bbb7, []int{0}
}

func (m *CursorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CursorRequest.Unmarshal(m, b)
}
func (m *CursorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CursorRequest.Marshal(b, m, deterministic)
}
func (m *CursorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CursorRequest.Merge(m, src)
}
func (m *CursorRequest) XXX_Size() int {
	return xxx_messageInfo_CursorRequest.Size(m)
}
func (m *CursorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CursorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CursorRequest proto.InternalMessageInfo

func (m *CursorRequest) GetCursor() string {
	if m != nil {
		return m.Cursor
	}
	return ""
}

func (m *CursorRequest) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type CursorResponse struct {
	// PreviousCursor is the cursor the client sent in their CursorRequest.
	PreviousCursor string `protobuf:"bytes,1,opt,name=previous_cursor,json=previousCursor,proto3" json:"previous_cursor,omitempty"`
	// NextCursor is the cursor clients should use to request the next page.
	NextCursor string `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	// Count is the page size, the number of elements in the page.
	Count                int32    `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CursorResponse) Reset()         { *m = CursorResponse{} }
func (m *CursorResponse) String() string { return proto.CompactTextString(m) }
func (*CursorResponse) ProtoMessage()    {}
func (*CursorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_89006c53d509bbb7, []int{1}
}

func (m *CursorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CursorResponse.Unmarshal(m, b)
}
func (m *CursorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CursorResponse.Marshal(b, m, deterministic)
}
func (m *CursorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CursorResponse.Merge(m, src)
}
func (m *CursorResponse) XXX_Size() int {
	return xxx_messageInfo_CursorResponse.Size(m)
}
func (m *CursorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CursorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CursorResponse proto.InternalMessageInfo

func (m *CursorResponse) GetPreviousCursor() string {
	if m != nil {
		return m.PreviousCursor
	}
	return ""
}

func (m *CursorResponse) GetNextCursor() string {
	if m != nil {
		return m.NextCursor
	}
	return ""
}

func (m *CursorResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterEnum("alpacalabs.pagination.v1.Sort", Sort_name, Sort_value)
	proto.RegisterType((*CursorRequest)(nil), "alpacalabs.pagination.v1.CursorRequest")
	proto.RegisterType((*CursorResponse)(nil), "alpacalabs.pagination.v1.CursorResponse")
}

func init() {
	proto.RegisterFile("alpacalabs/pagination/v1/page.proto", fileDescriptor_89006c53d509bbb7)
}

var fileDescriptor_89006c53d509bbb7 = []byte{
	// 314 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x51, 0xcd, 0x6a, 0xf2, 0x40,
	0x14, 0xfd, 0x12, 0x3f, 0xa5, 0xde, 0x56, 0x0d, 0x83, 0x94, 0x2c, 0x0a, 0x15, 0xbb, 0xa8, 0x14,
	0x9c, 0x10, 0xba, 0xea, 0xa2, 0x0b, 0x8d, 0x0a, 0x82, 0xb4, 0x21, 0x69, 0x5d, 0x14, 0x41, 0x62,
	0x18, 0x6c, 0x40, 0x73, 0xa7, 0x99, 0x89, 0xf4, 0x79, 0xba, 0xec, 0xbe, 0x2f, 0xd1, 0xa7, 0x2a,
	0x19, 0x6b, 0xc7, 0x16, 0x5c, 0x9e, 0x73, 0xcf, 0x0f, 0x9c, 0x0b, 0x17, 0xd1, 0x8a, 0x47, 0x71,
	0xb4, 0x8a, 0x16, 0xc2, 0xe1, 0xd1, 0x32, 0x49, 0x23, 0x99, 0x60, 0xea, 0x6c, 0xdc, 0x02, 0x31,
	0xca, 0x33, 0x94, 0x48, 0x6c, 0x2d, 0xa2, 0x5a, 0x44, 0x37, 0x6e, 0xfb, 0x16, 0x6a, 0x5e, 0x9e,
	0x09, 0xcc, 0x02, 0xf6, 0x92, 0x33, 0x21, 0xc9, 0x29, 0x54, 0x62, 0x45, 0xd8, 0x46, 0xcb, 0xe8,
	0x54, 0x83, 0x6f, 0x44, 0x9a, 0x50, 0x8e, 0x31, 0x4f, 0xa5, 0x6d, 0xb6, 0x8c, 0x4e, 0x39, 0xd8,
	0x82, 0x36, 0x87, 0xfa, 0xce, 0x2e, 0x38, 0xa6, 0x82, 0x91, 0x4b, 0x68, 0xf0, 0x8c, 0x6d, 0x12,
	0xcc, 0xc5, 0xfc, 0x57, 0x50, 0x7d, 0x47, 0x6f, 0x0d, 0xe4, 0x1c, 0x8e, 0x53, 0xf6, 0x2a, 0x77,
	0x22, 0x53, 0x89, 0xa0, 0xa0, 0xbc, 0x3f, 0x8d, 0xa5, 0xbd, 0xc6, 0xab, 0x1b, 0xf8, 0x1f, 0x62,
	0x26, 0x49, 0x13, 0xac, 0xf0, 0x3e, 0x78, 0x98, 0x3f, 0xde, 0x85, 0xfe, 0xd0, 0x1b, 0x8f, 0xc6,
	0xc3, 0x81, 0xf5, 0x8f, 0x9c, 0xc0, 0x91, 0x62, 0x7b, 0xa1, 0x67, 0x19, 0xa4, 0x06, 0x55, 0x85,
	0x06, 0xc3, 0xd0, 0xb3, 0xcc, 0xfe, 0x87, 0x01, 0x67, 0x31, 0xae, 0xe9, 0xa1, 0x31, 0xfa, 0x0d,
	0xff, 0x07, 0xfa, 0xc5, 0x6e, 0xbe, 0xf1, 0x34, 0x5a, 0x26, 0xf2, 0x39, 0x5f, 0xd0, 0x18, 0xd7,
	0x4e, 0x4f, 0xf9, 0x26, 0x6a, 0xe9, 0xe2, 0x9c, 0x31, 0x8e, 0x5d, 0x9d, 0xd0, 0x5d, 0xa2, 0x73,
	0xe8, 0x19, 0x6f, 0x66, 0xa9, 0x37, 0xf1, 0xdf, 0x4d, 0x5b, 0x67, 0x50, 0x5d, 0x46, 0xa7, 0xee,
	0xe7, 0xfe, 0x69, 0xa6, 0x4f, 0xb3, 0xa9, 0xbb, 0xa8, 0xa8, 0xb6, 0xeb, 0xaf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x24, 0x40, 0x6c, 0x87, 0xeb, 0x01, 0x00, 0x00,
}
